[build]
  command = "make build && ls && ls ./functions/ && ls ./functions/bin/ && cd functions/bin && pwd && ls /opt/build/repo/functions && echo 123 && ls /opt/build/repo/functions/bin"
  functions = "functions/bin"
  publish = "public"
[build.environment]
  GO_IMPORT_PATH = "github.com/macintoshpie/mxtp"