[build]
  command = "make build && ls && ls ./functions/ && ls ./functions/bin/"
  functions = "./functions/bin"
  publish = "public"
[build.environment]
  GO_IMPORT_PATH = "github.com/macintoshpie/mxtp"